# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingportal', '0002_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='student_degree',
            field=models.IntegerField(default=15),
        ),
    ]
